### ISSUE TITLE
Export of images inside editor (TinyMCE) blocks looses important class data

### ISSUE THREAD

**Issue by Bellfalasch** [enonic/cms2xp#13]
In CMS you could insert images inside the HTML editor and set different classes for the image to get different formats out on the website. Formats like "thumbnail", or the "custom" size slider where the users sets a specific width.

This data is added to each image as a class, class data like ".thumbnail" and ".no-scale-up" and such are then used in the site CSS to style these images depending on how the editor wanted it.

This setting/data needs to be migrated. Even if XP doesn't support custom image sizes yet, the classes for the img-tag in html needs to be migrated over so that not all images looks huge in XP (size the CSS no longer can find the classes to style for).

This is requested by Höegh Autoliners migration, made by Item Consulting. They have 100s of images spread across 60+ articles using different classes/formats. Mostly "thumbnail", but also a lot of "custom" ones.

From CMS - Looks good in CMS thanks to CSS
<img width="401" alt="screen shot 2017-06-27 at 09 48 39" src="https://user-images.githubusercontent.com/1465598/27577686-e2665920-5b21-11e7-8464-78496fdb4dd5.png">

From CMS - Classes are added that makes the CSS work
<img width="618" alt="screen shot 2017-06-27 at 09 49 04" src="https://user-images.githubusercontent.com/1465598/27577687-e26cec86-5b21-11e7-9867-23029ca439cc.png">

In XP the classes are gone, all images gets spread up to 100% width, impossible to scale down all to a set size since all are inserted with different settings. Just saying `.editor img { width: 200px; }` will fix 20% of the images but make the other 80% look ugly.

The different formats for images in CMS:
<img width="327" alt="screen shot 2017-06-27 at 10 28 01" src="https://user-images.githubusercontent.com/1465598/27578113-6268c698-5b23-11e7-85c5-dd1eb3b39823.png">

From CMS - How using custom size works, also important data not migrated today:
<img width="473" alt="screen shot 2017-06-27 at 10 28 14" src="https://user-images.githubusercontent.com/1465598/27578112-6266c406-5b23-11e7-8235-8a635c909c50.png">

How source looks in CMS after inserting a thumbnail:
```html
<p>xxx.</p>
<p class="editor-p-block"><img title="etag" src="image://86906?_size=thumbnail" alt="etag" /></p>
<p>xxx</p>
```

This is the result in CMS source for inserting a custom size image:
```html
<img alt="twitter" src="image://85058?_size=custom&amp;_filter=scalewidth(365)" title="twitter" />

```

So I assume STK being a big part of transforming this into classes and such. But almost no client is not using the STK.

**Comment by aro** [comment]
We will export the image styles:
- keeping the size parameter as a class in the figure element.
- for the scaled images, set the width (relative or absolute) as a style CSS attribute
- translate existing classes added: editor-image-left -> editor-left

```
<figure class="editor-left thumbnail|list|square" style="width:450px;">
	<img src="image://c137bb3a-19ee-4cd4-bb7f-b3f34056ee71" />
	<figcaption>Image caption text</figcaption>
</figure>
```
