### ISSUE TITLE
Menu items of type URL aren't migrated properly

### ISSUE THREAD

**Issue by Bellfalasch** [enonic/cms2xp#23]
In XP we don't support creating content of type URL redirect (as in CMS) out-of-the-box. In CMS you could create menu items of that type to send users to a completely different URL, like vg.no or enonic.com from market.enonic.com. To support this in XP one must use the [lib-urlredirect](https://github.com/enonic/lib-urlredirect) or similar. With it we get a new contenttype that lets you write a URL and visiting it will redirect you to that URL.

For big sites, that has loads and loads of redirects added as content in CMS, we loose a lot of valuable data in the migration. Could we detect the site setting (or the occurrence of any item of type URL) and then add the lib-urlredirect to the migrated app and use that content type instead?

Alternatively expand the shortcut contenttype in XP to support external URLs, or add another native contenttype for external links/redirects.

CMS2XP just converts these URL types to normal Pages and drops the URL data all together.

**Comment by sigdestad** [comment]
Bobby: I guess this is exactly the same "issue" as we need here: https://github.com/enonic/site-developer/issues/54 ?

**Comment by Bellfalasch** [comment]
Almost. But CMS2XP drops the data so I cannot fetch it at all in XP, so that's a big problem right now. So we need CMS2XP to migrate that data too (the URL itself), and preferable as a contenttype of type URL from lib-urlredirect (or built into future XP native shortcut contenttype).

**Comment by Bellfalasch** [comment]
lib-urlredirect is now updated to 2.0 using a controller mapping instead of a template. Also contains other improvements. Use it (it's on the market, and on github). The nav-app is already using it and ready for new content export.
