### ISSUE TITLE
Parts are generated out of XSLT-files - how does multi-use function?

### ISSUE THREAD

**Issue by Bellfalasch** [enonic/cms2xp#30]
We seem to have issues sometimes with parts being created out of XSLT-files that are used in multiple portlets. Common CMS practise was to have maybe 1 XLST-file that was use in -let's say - 20 different portlets. The difference being the config. In XP world this would be 1 Part, used in 20 different scenarios (different config). Is this at all taken into account in migration? We have indications suggesting it is not.

Ideally the parts would not be created into many different ones, but into only one.

**Comment by hjelmevold** [comment]
Example from NAV CMS installation:

Portlet based on the following XSLT file:
/beta.nav.no/modules/velg-skjema.xsl
…is used by all of these portlets:

- Skjema 3: Velg skjema
- Skjema 3: Velg skjema (AAP)
- Skjema 3: Velg skjema (AAP) (ettersendelse)
- Skjema 3: Velg skjema (Foreldrepenger)
- Skjema 3: Velg skjema (Foreldrepenger) Ettersendelse
- Skjema 3: Velg skjema (bank)
- Skjema 3: Velg skjema (bilstonad)
- Skjema 3: Velg skjema (bilstonad) (ettersendelse)
- Skjema 3: Velg skjema (pensjon)
- Skjema 3: Velg skjema (tilleggsstønader)
- Skjema 3: Velg skjema (tilleggsstønader) (ettersendelse)

This XSLT file contains 3 params of type page, and every portlet in the list above has different menuitems added to these params. See for example the portlet "Skjema 3: Velg skjema (AAP)" which has been added to the custom Page Configuration on this menuitem:
/no/Person/Skjemaer-for-privatpersoner/Skjemaer/Arbeid, helse og sykdom/arbeidsavklaringspenger/Arbeidsavklaringspenger

**Comment by sigdestad** [comment]
Just create a "view/" folder, and place the new template there. Then create a velg-skjema.js in the lib/ folder. this js will use the view template. For each part, simply require the velg-skjema.js and kick off the functions in the shared js file (maybe even using parameters)

**Comment by Bellfalasch** [comment]
@sigdestad The problem we're describing here is basically #32 - that after migration, <xsl:params> are not migrated to XP. These contain very important data and configuration for Portlets.These are lost in the migration process (in XP the Parts comes out without any config).

This issue is probably a bit "messy", but it is about doing extra research in CMS2XP code how these XSLT-files are handled. Just to make sure nothing else have sneaked in there too (other then what is outlined in #32) since this was common praxis in CMS (use one XSLT in multiple Portlets, just changing params).

**Comment by aro** [comment]
This might have been fixed in #32. Basically the portlet parameters were not converted at all in the generated parts.

**Comment by Bellfalasch** [comment]
@hjelmevold - This one looks to work as intended now right?
