### ISSUE TITLE
Configurable export that keeps unapproved drafts

### ISSUE THREAD

**Issue by hjelmevold** [enonic/cms2xp#33]
cms2xp exports all approved content, and disregards any unapproved drafts if there already is an approved version. Perhaps there could be an option to also export all unapproved drafts in a separate cms_content export folder, so the cms2xp process ends up generating folders cms_content_draft, cms_content_approved, cms_users and the app folder?

<img width="1113" alt="content-cms-approved" src="https://user-images.githubusercontent.com/354917/36781164-64208390-1c75-11e8-90a3-d8e08bc8c55c.png">
<img width="1112" alt="content-cms-latest-draft" src="https://user-images.githubusercontent.com/354917/36781165-6436ccd6-1c75-11e8-8037-6d21b4767220.png">
<img width="297" alt="content-xp-is-from-approved" src="https://user-images.githubusercontent.com/354917/36781166-6451d09e-1c75-11e8-9728-b47fdbc003f3.png">

**Comment by Bellfalasch** [comment]
Summary: Content in CMS with drafts not yet approved, will export only the approved version, dropping any changes from the draft, with CMS2XP. This could potentially be bad, since information is lost.

**Comment by aro** [comment]
The reason is that XP export format does not supports versions. The dump format does, but then you have to overwrite all the data in XP. The dump format is also more complex to generate.

Options:
- generate 2 exports, one for draft and one for master. This can be a bit tricky
- generate 1 export like now, and add publishing status metadata as a mixin

**Comment by sigdestad** [comment]
I propose we skip this and write in the CMS2XP doc that only the latest and approved version of content will be exported. 

Ok?

**Comment by hjelmevold** [comment]
won't fix. we only migrate current versions.
