### ISSUE TITLE
Shortcut menu item URL name conflict with destination menu item

### ISSUE THREAD

**Issue by hjelmevold** [enonic/cms2xp#34]
Given the following shortcut menuitem in CMS:
Sites / www.nav.no / Menu items / no / Person / Arbeid / Jobbsøkertips
…with Display name "Jobbsøkertips" and Destination page:
Sites / www.nav.no / Menu items / no / Person / Arbeid / Jobbsokertips

…wrongly gets the URL name of its destination page
/sites/www.nav.no/no/person/arbeid/jobbsokertips
(and not what it should be: /no/Person/Arbeid/Jobbsøkertips)

Hence, the destination page which also has URL name Jobbsokertips gets the path
/sites/www.nav.no/no/person/arbeid/jobbsokertips_2
by accident after export. (it should have been /no/Person/Arbeid/Jobbsokertips

By the way, is it correct that the URL path is converted to lowercase??? Perhaps this is part of the same issue? Unnecessary transliteration and lowercase?

**Comment by Bellfalasch** [comment]
Two things:
* URLs containing uppercase chars in CMS are forced to lowercase in XP.
* URLs containing åäö (and other local characters) gets forcibly transliterated in XP.
We awesome both these changes happening during CMS2XP's processing of the data.

**Comment by aro** [comment]
Yes, the content name generation in XP makes lowercase and transliterates those chars. Cms2xp does not attempt to keep the same URLs as in CMS.

Now we just apply the same transliteration process to the contents created. We could have special handling for menu-items in CMS2XP. 

I think URL functions in XP percent-encode åäö in a path. We should check that.

**Comment by alansemenov** [comment]
This can be solved by manually changing content path.
