### ISSUE TITLE
Use new publish.from publish.to format for content publish info

### ISSUE THREAD

**Issue by Bellfalasch** [enonic/cms2xp#4]
CMS had publish-settings for From and To. This was not introduced into XP until 6.9. This migration tool handles this by creating a mixin for publishing information, and storing that data there.

It would be a cleaner solution to now use this new format used in 6.9. If backwards-compatability is needed (in the 6.x series) we need to sniff out support, or add a `target` setting for XP version and handle < 6.9 like now, and 6.9+ in the new way.

**Comment by sigdestad** [comment]
No need to think about backward compatibility here..

Vennlig hilsen/Best regards 

Thomas Sigdestad
CTO & Co-Founder
+47 98236011

https://enonic.com - A web operating system for your sites and applications
