### ISSUE TITLE
Using "moveHomeContentToSection" (true) doesn't work as intended

### ISSUE THREAD

**Issue by Bellfalasch** [enonic/cms2xp#6]
The data is kept in all locations (for 4 checked keys, they all existed in at least two locations). That is not very problematic, however the keys/ids are identical. And thus, the import tool will skip one of them. Looks like the last one, and that looks like the data we actually wanted to keep (as it is placed where CMS has set its "home") and the part (or fragment?) references to it from the other locations.

Setting to false works. But it is a handy feature so would be nice to get it to work.

A search in the exported data gives me two hits on this, for example:
`<id>e589ed54-11c2-4d53-b938-aa2bf259ec1c</id>`

**Comment by Bellfalasch** [comment]
Do you need any more input on this? I guess it is still a problem in 0.8.1.

**Comment by aro** [comment]
No, I get the problem. It's still not fixed on 0.8.1. I will try to look into this next week.

**Comment by aro** [comment]
Fixed the duplication of the node in all the sections. Now after a content is exported to a section location it won't be set anywhere else.

There is no control regarding in which section it will be set. I am open for suggestions about how to indicate the desired target section, if it's important.
